#!/bin/bash
notify-send -i $notifyIcon "Firewall disabled all traffic will be allowed";
sudo ufw --force reset;
sudo rm -f /etc/ufw/{before,before6,after,after6,user,user6}.rules.*;
sudo ufw disable;
