#!/bin/bash

for intf in /sys/class/net/*; do
	sudo ifconfig $(basename "$intf") down
done

sudo service tor stop
sudo service openvpn stop
sudo killall tor openvpn
sudo service network-manager stop

notify-send -i "$notifyIcon" "All network devices have been disabled"

exit 0
