#!/bin/bash
echo "This will enable NetworkManager"
sudo systemctl start NetworkManager
if [ "$?" != "0" ]; then
	echo "Systemctl failed, trying with service..."
	sudo service NetworkManager start
	if [ "$?" != "0" ]; then
		echo "Everything failed, trying something else..."
	else
		echo "Done!"
	fi
else
	echo "Done!"
fi
