#!/bin/bash
#
#

#cd $(dirname $0)
#source Globalconfig;

for intf in /sys/class/net/*; do
	sudo ifconfig `basename $intf` up
	notify-send -i $notifyIcon "Bringing $intf up";
done
sudo service network-manager restart;
notify-send -i $notifyIcon "All network devices have been enabled";
exit 1;
