#!/bin/bash

echo "This will disable NetworkManager, possibly avoiding the random dropping of IPs"
sudo systemctl stop NetworkManager || sudo service NetworkManager stop

if [ "$?" != "0" ]; then
	echo "Both systemctl and service failed to stop NetworkManager."
else
	echo "NetworkManager stopped successfully."
fi
