#!/bin/sh
country=(whois $(dig +short myip.opendns.com @resolver1.opendns.com) | awk ' /[Cc]ountry/{print $2}')"

echo "Changing rate-mirrors mirror list form global to $country"
sed -i 's/using rate-mirrors,/using rate-mirrors for $country and close Neighbours,/' /usr/lib/garuda/garuda-update/main-update
sed -i 's/&& rate-mirrors --allow-root/&& rate-mirrors --protocol https --max-jumps 1 --concurrency 5 --entry-country $country --country-test-mirrors-per-country 7 --country-neighbors-per-country 1 --allow-root/' /usr/lib/garuda/garuda-update/main-update

echo "Changing reflector mirror list from global to $country"
sed -i 's/using reflector,/using reflector for $country,/' /usr/lib/garuda/garuda-update/main-update
sed -i 's/--age 2 --fastest/--age 2 --country $country --fastest/' /usr/lib/garuda/garuda-update/main-update
