#!/usr/bin/env python3

from Mimeo import Mimeo
from sys import argv

mimeo = Mimeo()
for mimetype in sorted(set(argv[1:])):
    print(mimetype)
    desktops = mimeo.get_associated_desktop_names(mimetype)
    print("\t" + "\n\t".join(desktops) if desktops else "None")
