#!/usr/bin/env python3

import sys
import json
import socket

def send_command(command, param=None):
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect("/tmp/mpvsocket")

    if param:
        data = {"command": [command, param]}
    else:
        data = {"command": [command]}

    sock.send(json.dumps(data).encode("utf-8"))
    response = sock.recv(4096).decode("utf-8")
    sock.close()

    return json.loads(response)

if len(sys.argv) < 2:
    print("Usage: mpv-ipc command [param]")
    sys.exit(1)

command = sys.argv[1]
param = sys.argv[2] if len(sys.argv) > 2 else None
response = send_command(command, param)

if "error" in response and response["error"] != "success":
    print("Error:", response["error"])
else:
    print(response.get("data", ""))
