#!/bin/bash

tCount=$(sudo lsof -i -P -n | grep LISTEN | wc -l)

notify-send -i $notifyIcon "Showing $OS_name open ports: $tCount in total"

while true; do
    clear
    echo "Showing $OS_name $tCount open ports:"
    echo ""
    sudo lsof -i -P -n | grep LISTEN
    echo "--------------------------------------------------------------------------------------------------"
    echo ""
    sudo netstat -tulpn | grep LISTEN
    echo "--------------------------------------------------------------------------------------------------"
    sleep 30
done

exit 1
