#!/bin/bash

progress_bar()
{
  local DURATION=$1
  local INT=0.25      # refresh interval
 
  local TIME=0
  local CURLEN=0
  local SECS=0
  local FRACTION=0
 
  local FB=2588       # full block
 
  trap "echo -e $(tput cnorm); trap - SIGINT; return" SIGINT
 
  echo -ne "$(tput civis)\r$(tput el)│"                # clean line
 
  local START=$(date +%s%N)
 
  while [ $SECS -lt $DURATION ]; do
    local COLS=$(tput cols)
 
    # main bar
    local L=$(awk -v c="$COLS" -v t="$TIME" -v d="$DURATION" -v i="$INT" 'BEGIN {printf "%.2f", (c - 5) * t / (d - i)}')
    local N=$(awk -v l="$L" 'BEGIN {printf "%d", int(l)}')
 
    [ $FRACTION -ne 0 ] && echo -ne "$(tput cub 1)"  # erase partial block
 
    if [ $N -gt $CURLEN ]; then
      for i in $(seq 1 $((N - CURLEN))); do
        echo -ne \\u$FB
      done
      CURLEN=$N
    fi
 
    # partial block adjustment
    FRACTION=$(awk -v l="$L" 'BEGIN {printf "%.0f", (l - int(l)) * 8}')
 
    if [ $FRACTION -ne 0 ]; then 
      local PB=$(printf %x $((0x258F - FRACTION + 1)))
      echo -ne \\u$PB
    fi
 
    # percentage progress
    local PROGRESS=$(awk -v t="$TIME" -v d="$DURATION" -v i="$INT" 'BEGIN {printf "%.0f", 100 * t / (d - i)}')
    echo -ne "$(tput sc)"                            # save pos
    echo -ne "\r$(tput cuf $((COLS - 6)))"         # move cur
    echo -ne "│ $PROGRESS%"
    echo -ne "$(tput rc)"                            # restore pos
 
    TIME=$(awk -v t="$TIME" -v i="$INT" 'BEGIN {printf "%.2f", t + i}')
    SECS=$(awk -v t="$TIME" 'BEGIN {printf "%d", int(t)}')
 
    # take into account loop execution time
    local END=$(date +%s%N)
    local DELTA=$(awk -v i="$INT" -v s="$START" -v e="$END" 'BEGIN {printf "%.9f", i - ((e - s) / 1000000000)}')
    sleep $DELTA
    START=$(date +%s%N)
  done
 
  echo $(tput cnorm)
  trap - SIGINT
}
