#!/usr/bin/env bash

if [[ "$EUID" = 0 ]]; then
    echo "(1) already root"
else
    sudo -nk # make sure to ask for password on next sudo
    if sudo -n true; then
        echo "(2) correct password"
    else
        echo "(3) wrong password"
        exit 1
    fi
fi

sudo journalctl --vacuum-time=3d
echo "Clear journalctl: OK"

sudo find ~/.cache/ -type f -atime +3 -delete
echo "Clear cache: OK"

sudo rm -vrf ~/.local/share/Trash/*
echo "Clear Trash: OK"

sudo docker image prune -f || true
echo "Clear docker: OK"

echo "Clean: OK"
