#!/bin/bash

# Get actual IP address
actual_ip=$(dig +short myip.opendns.com @resolver1.opendns.com)

# Get public IP address
public_ip=$(curl -s https://ipinfo.io/ip)

echo "Actual IP address: $actual_ip"
echo "Public IP address: $public_ip"

exit 0
